### ISSUE TITLE
Component fails to list results after route change

### ISSUE THREAD

**Issue by mwargan** [MadimetjaShika/vuetify-google-autocomplete#26]
Hey :P!

It looks like the component is failing to show results after a route change - see https://github.com/mwargan/vuetify-google-autocomplete-simple-example (added a router)

Nothing in the console - gets me thinking if there's any better debugging tool for Vue I could acquire.

Let me know if I can provide more info!

**Comment by ewwwgiddings** [comment]
I am having the same issue. When loading directly it works. With route change it fails.

**Comment by MadimetjaShika** [comment]
Hey guys,

Thanks for pointing this out. I’ll only get a chance to have a look at this
sometime this coming weekend if not early next week. If any of you guys are
keen on checking it out, you’re welcome to create a PR and I’ll merge it in.

**Comment by timothynott** [comment]
Doesn't need to be a route change. I've got the component in a wizard step and if I go back (not using history) it also stops working. I've run a few tests on the events in the component and they all seem to be responding. I'm wondering if this is actually an issue with Google's code. I've had a similar issue with the Google Maps SDK in the past. Looking into it.

**Comment by timothynott** [comment]
I adjusted my code to use a v-show instead of v-if for the blocks I was showing/hiding for the wizard and that did the trick. My guess right now is that "googeMapState.initMap" does not get re-triggered and so setupGoogle() does not run

**Comment by timothynott** [comment]
[pull req submitted](https://github.com/timothynott/vuetify-google-autocomplete)

Would be interested to hear if this fixes the issue for route changes, as well.

**Comment by MadimetjaShika** [comment]
Hi @timothynott 

Thanks for the PR, much appreciated! I've merged it in, i'm going to publish a new version just now and will let you know once done.

**Comment by MadimetjaShika** [comment]
I've published the fix under alpha version ``vuetify-google-autocomplete@2.0.0-Alpha.6``.

@mwargan and @ewwwgiddings, please let me know if this resolves the route change issue that you had.

**Comment by ewwwgiddings** [comment]
When I load the site on localhost then first thing navigate to the autocomplete's page it does not work. When I load the site and then go to the autocomplete's page indirectly it does work now.

So yes it works better now, and I think it is something with my code that is causing that buggy situation, not with this. I will be looking into why probably some time this week. If I find it to be something other than my code I will let you know. Otherwise, thank you!

**Comment by mwargan** [comment]
Looks like I'm still running into the issue. As mentioned above, it does work better, so a big thumbs up for your continual efforts 👍!

Interestingly, I've noticed that v6 works when routes change as long as the router is saved under a `keep-alive`. Not yet sure if related, but the first component with autocomplete to load and with keep-alive works great (even after some nav), but if I have another component on another page, that one seems to fail. Will dig deeper and try it out with the simple example you provided and I linked above as soon as I get more time!

**Comment by MadimetjaShika** [comment]
Cool thanks guys. I'll look into this sometime this weekend and let you know when resolved.

**Comment by santanubasu** [comment]
Any update on this one?  The component works great otherwise, but this one issue is preventing us from using this in production.

**Comment by timothynott** [comment]
Submitted another PR tested against route changes with vue-router.

**Comment by MadimetjaShika** [comment]
@timothynott thanks so much for the PR! I've merged and published new version ``2.0.0-Alpha.7`` 👍

I've tested this with route changes and it seems to be working okay now. Thanks again @timothynott!

**Comment by timothynott** [comment]
Happy to help

**Comment by santanubasu** [comment]
Good stuff, thanks guys.  Confirming that this resolves the issue on route change for me.

**Comment by MadimetjaShika** [comment]
Closing this issue as resolved. Feel free to re-open if still experiencing the same problem.

**Comment by ledermann** [comment]
Just stumble about this issue still present in 2.0.0-beta.4: On first load all is fine, after route changing the result list stays empty. PR #31 seems to be not enough.

Here is my code (of a component using vga, reduced to relevant parts) including a hack to execute `setupGoogle` on mounting my component:

```vue
<template>
  <vuetify-google-autocomplete
      id="map"
      ref="myAddress"
  >
  </vuetify-google-autocomplete>
</template>

<script>
  export default {
    data: () => ({
      myAddress: ''
    }),

    mounted() {
      // Hack, see https://github.com/MadimetjaShika/vuetify-google-autocomplete/issues/26
      if (window.hasOwnProperty('google') && window.google.hasOwnProperty('maps')) {
        this.$refs.myAddress.setupGoogle();
      }
    },
  }
</script>
```
With the hack in `mounted` it all works fine.

Versions used:

* Vue 2.5.16
* Vuetify 1.1.4
