### ISSUE TITLE
Dependencies not found 'babel-runtime/core-js/object/keys'

### ISSUE THREAD

**Issue by AlissonRS** [MadimetjaShika/vuetify-google-autocomplete#73]
I installed and followed the instructions, but when I try to serve the project, I get this:

```
These dependencies were not found:

* babel-runtime/core-js/object/keys in ./node_modules/vuetify-google-autocomplete/lib/helper.js
* babel-runtime/helpers/typeof in ./node_modules/vuetify-google-autocomplete/lib/helper.js
```

How can I solve this? Thanks.

**Comment by alexcroox** [comment]
Also running into this with 2.0.0-beta.6

**Comment by 0pn** [comment]
Same here. Any feedback on this?

**Comment by alsconsulting** [comment]
I fixed this issue by installing babel-runtime as a dev dependency.

**Comment by NijasHameed** [comment]
Is there any workaround available for this, I have tried with babel-runtime but still not working.

**Comment by NijasHameed** [comment]
@AlissonRS Have you find anything?

**Comment by elik56a** [comment]
`npm install --save @babel/runtime ` doesnt solve the problem.
someone can help?

**Comment by robertonsend** [comment]
try `npm install babel-plugin-transform-runtime`

It seems fix my one, but somehow yarn does not like the solution.

**Comment by elik56a** [comment]
@robertonsend thanks man!! work perfectly!!

**Comment by MadimetjaShika** [comment]
Hi, this should be resolved in ``v2.0.0`` of this library.

The observed error was due to babel transforming all instances of ``Object.keys`` and ``typeof`` to  babel's ``transform-es2015-object-super`` and ``"transform-es2015-typeof-symbol`` versions respectively. This added ``babel-runtime`` as a dependency to the transpilled source, meaning you'd need to have ``babel-plugin-transform-runtime`` in your project to use this library. I've removed ``transform-runtime`` from the babel config, which prevents ``babel-plugin-transform-runtime`` from being added as a dependency.

Feel free to re-open this if you still get any issues.
