### ISSUE TITLE
The computed property "fields" is already defined as a prop

### ISSUE THREAD

**Issue by butaminas** [MadimetjaShika/vuetify-google-autocomplete#91]
Gettings this whenever I init the autocomplete field.

I don't have any computed properties by the name "fields". But if I change "fields" prop to something else, I no longer get this error.

**Comment by bhavini-chauhan** [comment]
We are getting the same error. Does anyone has the solution to this.?

**Comment by MadimetjaShika** [comment]
Hi guys, please could you share some sample code which causes the error you're observing? I'm having trouble reproducing this error.

**Comment by bhavini-chauhan** [comment]
This is only the vue warning.
Whenever the google autocomplete is initialized. 
We are getting this error in the console.

"vue": "^2.6.11",
"vue-template-compiler": "^2.6.11",
"vuetify": "^2.1.15",
"vuetify-google-autocomplete": "^2.0.0-beta.6",


![Screenshot from 2019-12-31 12-31-32](https://user-images.githubusercontent.com/57613186/71612953-9bc4ac80-2bc9-11ea-8eba-6afc4d100073.png)

**Comment by MadimetjaShika** [comment]
Hi @Bhavini30 , please update to ``v2.0.0-beta.8`` or ``v2.0.0`` (which i've published today). There potentially could've been a problem with ``v2.0.0-beta.6``.

@butaminas, please confirm if you're also using the same versions as mentioned by @Bhavini30, and confirm if updating to the latest version helps.

**Comment by bhavini-chauhan** [comment]
Hi @MadimetjaShika ,
I have updated the vuetify-google-autocomplete version to v2.0.0-beta.8 or v2.0.0. But still  I am facing the same error.

**Comment by MadimetjaShika** [comment]
That's pretty odd. Can you share some sample code or repo that causes the warning? I'm having a hard time reproducing that warning, it's also not present on the [example app](https://madimetjashika.github.io/vuetify-google-autocomplete/) as in the screenshot below - specifically on initialisation.

<img width="1680" alt="Screenshot 2020-01-01 at 09 16 12" src="https://user-images.githubusercontent.com/6643245/71639026-755d4a80-2c77-11ea-9fad-e016d1ea96f8.png">

If I may also suggest, please have a look in your ``node_modules`` folder and ensure that the version of ``vuetify-google-autocomplete`` in there is actually ``2.0.0`` (check the ``package.json`` file), and that you aren't possibly running a stale version, alternatively delete the node_modules folder and run your dependency install without cache, e.g. ``npm install --no-cache``. I see you're also using Laravel, please make sure that the static built assets are also not stale after your install.

**Comment by butaminas** [comment]
@MadimetjaShika 

I also use the latest version. As a workaround, I am now using this plugin as a local component and I changed the "fields" prop to `returnFields`. This way I don't get the error anymore.

**Comment by bryanlampert** [comment]
I've been receiving this error in the console as well.
Just updated to 2.0.0 and the error still persists.

**Comment by MadimetjaShika** [comment]
Hi guys,

It's difficult to assist without some code examples. Please share some code examples on how you're using this library so I can reproduce the problem. Or share a reproduction repo.

**Comment by mayank30** [comment]
Hi Guys, 
Also facing the same issue, with latest version, we are using vuetify and some other dependency suddenly observe the same error. 

![image](https://user-images.githubusercontent.com/6511688/73970822-1ea1fb00-491e-11ea-9479-2a7c2390c261.png)

```
Vue.use(VuetifyGoogleAutocomplete, {
  apiKey: googleAPIKey
});

@Component({
  name: "googleAddress",
  inject: ["$validator"],
  data() {
    return {
      address: "",
      city: "",
      state: "",
      country: "",
      isDisabled: true,
      addressComponents: {
        country: "",
        state: "",
        city: ""
      }
    };
  },
  props: {
    error: {
      type: String
    },
    prefix: {
      type: String
    },
    suffix: {
      type: String
    },
    label: {
      type: String
    },
    helpText: {
      type: String
    },
    type: {
      type: String,
      default: "text"
    },
    required: {
      type: Boolean
    },
    disabled: {
      type: Boolean,
      default: false
    },
    placeholder: {
      type: String
    },
    name: {
      type: String
    },
    minlength: {
      type: String
    },
    maxlength: {
      type: String
    },
    add: {
      type: Object,
      default: () => ({
        addressStr: "",
        address: {
          country: "",
          city: "",
          state: ""
        }
      })
    }
  },
  created() {
    this.$validator = this.$parent.$validator;
  }
})
-------------

<vuetify-google-autocomplete
          id="map"
          types="establishment"
          :placeholder="placeholder"
          v-on:placechanged="getAddressData"
          :country="countriesPermitted"
          v-model="address"
        ></vuetify-google-autocomplete>

```

**Comment by nathany** [comment]
I was seeing this warning in the Chrome console after upgrading to v2.0.1 using the latest Vue 2.6.11 and Vuetify 2.2.12.

However, the `npm install --no-cache` [tip](https://github.com/MadimetjaShika/vuetify-google-autocomplete/issues/91#issuecomment-570029705) worked! Thanks.

**Comment by nathany** [comment]
Spoke too soon. The warning is back. May have disappeared for some other reason, as I'm still in the midst of updating Vuetify (the warning was there before I started).

**Comment by kempsteven** [comment]
Any news to this one?
Version:2.0.1

**here is a code sample**

```
<vuetify-google-autocomplete
     id="map"
      v-on:placechanged="getAddressData"
      placeholder="Please type your address"
      country="sg"/>
```
